version: "3"
services:
    db:
      container_name: db
      image: mysql
      # command: --default-authentication-plugin=mysql_native_password
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
      ports:
        - "3306:3306"  
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - MYSQL_DATABASE=facturation
      volumes:
        - /Users/bahad001/docker/db/mysql/data:/var/lib/mysql
